### PR TITLE
fix: production node-ts memory usage

### PR DESCRIPTION
**Pull request by SebFlippence**
### JIRA link ###

N/A

### Change description ###

Reduces production `ts-node` memory usage from around ~200 MiB to around ~70 MiB.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by linusnorton** [comment]
Won't we lose the typescript errors though?

**Comment by damongreen123** [comment]
> Won't we lose the typescript errors though?
Do you mean in the logs or the app @linusnorton ? the logs are empty.

**Comment by SebFlippence** [comment]
> Won't we lose the typescript errors though?

`yarn start` is used on production. So by this point it would have gone through `yarn start:dev` used locally, which will still show TypeScript errors. There's also the Jenkins build that runs `yarn build:prod` which would fail the build if there are any TypeScript errors.

`--transpile-only` looks like it does ignore type errors, but [reduces RAM by using a faster transpile module](https://medium.com/aspecto/ts-node-ram-consumption-12c257e09e13).

**Comment by linusnorton** [comment]
I was thinking about the stack trace, if we still have the stack trace then it's all good. Worth checking though!

**Review by linusnorton — APPROVED** [review]

**Comment by SebFlippence** [comment]
> I was thinking about the stack trace, if we still have the stack trace then it's all good. Worth checking though!

Logs, errors and stack traces are still reported (just the TypeScript warning/errors will be stripped, but they get checked by CI anyway :tada:)

**Pull request merged**
